### ISSUE TITLE
Upgrade project to WPILib v2022.2.1

### ISSUE THREAD

**Issue by nowireless** [Team2470/FRC-2022-robot#7]
https://github.com/wpilibsuite/allwpilib/releases/tag/v2022.2.1

**Comment by shetaye** [comment]
I updated `gradle.build` in 730c71ec10d8bfbf4d6e6414e542870a3891ce3e

**Comment by nowireless** [comment]
@shetaye can you open a pull request for the `feature/upgrade-wpilib` branch?
